"""add Department

Revision ID: 763eb0e2a345
Revises: 2117402f349b
Create Date: 2024-06-26 14:17:57.398655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763eb0e2a345'
down_revision = '2117402f349b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
