"""rename department

Revision ID: af7bb64b0ca3
Revises: 763eb0e2a345
Create Date: 2024-06-27 12:43:26.367063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7bb64b0ca3'
down_revision = '763eb0e2a345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
